// RotorQuant K=iso4 × V=turboq2_tcq (X-RQ-s2, K-RQ-30, HIGH, K>>V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_TCQ);
