// RotorQuant K=planar4 × V=turboq4 (X-RQ-s2, K-RQ-38, HIGH, K>V barely)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_TURBOQ4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_TURBOQ4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_TURBOQ4_0);
