// Mixed KV: turbo3_tcq K + f16 V

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_F16);
