// AUTO asym KV matrix: K=IQ4_NL (4.500bpw) V=TURBOQ3_0 (3.125bpw)  K-bpw>=V-bpw
#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ3_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ3_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ3_0);
DECL_FATTN_VEC_CASE(512, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ3_0);
