// RotorQuant K=planar3 × V=iso4 (X-RQ-s3, K-RQ-19, LOWER, K<V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_RQ_ISO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_RQ_ISO4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_RQ_ISO4_0);
