// AUTO asym KV matrix: K=TURBOQ6_0 (6.125bpw) V=TURBOQ3_TCQ (3.250bpw)  K-bpw>=V-bpw
#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ6_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ6_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ6_0, GGML_TYPE_TURBOQ3_TCQ);
