// TCQ KV: turbo3_tcq K + turbo3_tcq V (KV cache uses same type)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ3_TCQ);
