// RotorQuant K=planar4 × V=iso4 (X-RQ-s2, K-RQ-35, HIGH)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO4_0);
