// AUTO asym KV matrix: K=IQ4_NL (4.500bpw) V=TURBOQ2_TCQ (2.250bpw)  K-bpw>=V-bpw
#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_IQ4_NL, GGML_TYPE_TURBOQ2_TCQ);
