// Mixed KV: q4_0 K + turboq3_tcq V (X-2b-s2)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q4_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q4_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q4_0, GGML_TYPE_TURBOQ3_TCQ);
