// RotorQuant K=iso3 × V=planar4 (X-RQ-s3, K-RQ-9, LOWER, K<V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_ISO3_0, GGML_TYPE_RQ_PLANAR4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_ISO3_0, GGML_TYPE_RQ_PLANAR4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_ISO3_0, GGML_TYPE_RQ_PLANAR4_0);
