// Mixed KV: turbo2_tcq K + q8_0 V

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ2_TCQ, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ2_TCQ, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ2_TCQ, GGML_TYPE_Q8_0);
