// RotorQuant K=planar4 × V=iso3 (X-RQ-s2, K-RQ-36, HIGH, K>V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO3_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO3_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR4_0, GGML_TYPE_RQ_ISO3_0);
