// RotorQuant K=iso4 × TURBOQ2_INNERQ V (Phase X-InnerQ-s3, HIGH, K>=V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_INNERQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_INNERQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_ISO4_0, GGML_TYPE_TURBOQ2_INNERQ);
