// TURBOQ4_0 K × RotorQuant 3-bit planar V FA template instances

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ4_0, GGML_TYPE_RQ_PLANAR3_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ4_0, GGML_TYPE_RQ_PLANAR3_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ4_0, GGML_TYPE_RQ_PLANAR3_0);
