// Mixed TCQ KV: turbo3_tcq K + turbo2_tcq V

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ3_TCQ, GGML_TYPE_TURBOQ2_TCQ);
