// RotorQuant K=planar3 × V=turboq3_tcq (X-RQ-s3, K-RQ-17, LOWER, K<V barely)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_TURBOQ3_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_TURBOQ3_TCQ);
