// AUTO asym KV matrix: K=Q4_0 (4.500bpw) V=IQ4_NL (4.500bpw)  K-bpw>=V-bpw
#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q4_0, GGML_TYPE_IQ4_NL);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q4_0, GGML_TYPE_IQ4_NL);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q4_0, GGML_TYPE_IQ4_NL);
DECL_FATTN_VEC_CASE(512, GGML_TYPE_Q4_0, GGML_TYPE_IQ4_NL);
