// AUTO asym KV matrix: K=TURBOQ8_0 (8.125bpw) V=TURBOQ2_TCQ (2.250bpw)  K-bpw>=V-bpw
#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBOQ8_0, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBOQ8_0, GGML_TYPE_TURBOQ2_TCQ);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBOQ8_0, GGML_TYPE_TURBOQ2_TCQ);
