// RotorQuant K=planar3 × V=q8_0 (X-RQ-s3, K-RQ-22, LOWER, K<V)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ_PLANAR3_0, GGML_TYPE_Q8_0);
