// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

// Per-TU storage for the int8 WQ3_TCQ codebook + global scale. Co-locating
// the definition, the populator, and the reader (load_tiles_wq3_tcq) in this
// single TU sidesteps the `extern __constant__` / cross-TU symbol issue that
// would otherwise require nvcc `-rdc=true`. This is the only TU that
// instantiates mul_mat_q_case<GGML_TYPE_WQ3_TCQ> (via DECL_MMQ_CASE below),
// so TU-local storage is sufficient.
static __constant__ int8_t d_wq3_tcq_codebook_i8[1024];
static __constant__ float  d_wq3_tcq_codebook_scale;

void ggml_cuda_wq3_tcq_mmq_set_codebook_i8(const int8_t * h_codebook_i8, float scale) {
    CUDA_CHECK(cudaMemcpyToSymbol(d_wq3_tcq_codebook_i8, h_codebook_i8, 1024 * sizeof(int8_t)));
    CUDA_CHECK(cudaMemcpyToSymbol(d_wq3_tcq_codebook_scale, &scale, sizeof(float)));
}

// WQ3_TCQ load_tiles: trellis-decode the 3-bit bitstream into int8 codebook
// values, producing a tile layout byte-identical to Q8_0 so the downstream
// vec_dot_q8_0 MMA / DP4A kernels handle the matmul unchanged.
//
// Layout invariants (mirroring load_tiles_q8_0):
//   * 256-element k-tile per call == 2 WQ3_TCQ blocks (128 elems each).
//   * Per thread (txi in 0..31): write 1 int32 (4 packed int8) for block 0 at
//     x_qs[i*stride_x + txi] and 1 int32 for block 1 at x_qs[i*stride_x + 32 + txi].
//   * Scale slots (8 per row): all 4 slots for block 0 hold norm0*codebook_scale,
//     all 4 for block 1 hold norm1*codebook_scale — matches the per-32-elem
//     sub-block scale consumed by vec_dot_q8_0_q8_1_mma<..., D4>.
template <int mmq_y, bool need_check> static __device__ __forceinline__ void load_tiles_wq3_tcq(
    const char * __restrict__ x, int * __restrict__ x_tile, const int kbx0, const int i_max, const int stride) {
    constexpr int nwarps = mmq_get_nwarps_device();
    constexpr int warp_size = ggml_cuda_get_physical_warp_size();

#if defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
    int   * x_qs = (int   *)  x_tile;
    float * x_df = (float *) (x_tile + 2*MMQ_TILE_NE_K);
#else
    constexpr tile_x_sizes txs = mmq_get_dp4a_tile_x_sizes(GGML_TYPE_WQ3_TCQ, mmq_y);
    int   * x_qs = (int   *)  x_tile;
    float * x_df = (float *) (x_qs + txs.qs);
#endif // defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)

    constexpr int threads_per_row = 32;
    constexpr int nrows = warp_size / threads_per_row;
    const int txi = warp_size > threads_per_row ? threadIdx.x % threads_per_row : threadIdx.x;

#pragma unroll
    for (int i0 = 0; i0 < mmq_y; i0 += nrows*nwarps) {
        int i = i0 + (nrows == 1 ? threadIdx.y : threadIdx.y*nrows + threadIdx.x/threads_per_row);

        if (need_check) {
            i = min(i, i_max);
        }

        const block_turboq3_tcq * bxi = (const block_turboq3_tcq *) x + kbx0 + i*stride;

        // Decode 4 consecutive trellis states from each of 2 WQ3_TCQ blocks and
        // pack into two int32s. Sliding 10-bit window at bit_pos = t*3; the
        // [byte_idx+2] read is safe because qs[49] aliases the block's pad byte.
        uint32_t packed0 = 0;
        uint32_t packed1 = 0;
        #pragma unroll
        for (int j = 0; j < 4; ++j) {
            const int t = txi*4 + j;
            const int bit_pos = t*3;
            const int byte_idx = bit_pos >> 3;
            const int bit_off  = bit_pos & 7;

            const uint32_t raw0 = (uint32_t)bxi[0].qs[byte_idx]
                                | ((uint32_t)bxi[0].qs[byte_idx+1] << 8)
                                | ((uint32_t)bxi[0].qs[byte_idx+2] << 16);
            const int state0  = (raw0 >> bit_off) & 0x3FF;
            const int8_t c0   = d_wq3_tcq_codebook_i8[state0];
            packed0 |= ((uint32_t)(uint8_t)c0) << (j*8);

            const uint32_t raw1 = (uint32_t)bxi[1].qs[byte_idx]
                                | ((uint32_t)bxi[1].qs[byte_idx+1] << 8)
                                | ((uint32_t)bxi[1].qs[byte_idx+2] << 16);
            const int state1  = (raw1 >> bit_off) & 0x3FF;
            const int8_t c1   = d_wq3_tcq_codebook_i8[state1];
            packed1 |= ((uint32_t)(uint8_t)c1) << (j*8);
        }

#if defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
        x_qs[i*MMQ_MMA_TILE_X_K_Q8_0 + 0             + txi] = (int)packed0;
        x_qs[i*MMQ_MMA_TILE_X_K_Q8_0 + MMQ_TILE_NE_K + txi] = (int)packed1;
#else
        x_qs[i*(2*MMQ_TILE_NE_K + 1) + 0             + txi] = (int)packed0;
        x_qs[i*(2*MMQ_TILE_NE_K + 1) + MMQ_TILE_NE_K + txi] = (int)packed1;
#endif // defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
    }

    constexpr int blocks_per_tile_x_row = 2*MMQ_TILE_NE_K / QI8_0;   // 8 sub-block scale slots per row
    constexpr int rows_per_warp = warp_size / blocks_per_tile_x_row; // 4
    const int kbxd = threadIdx.x % blocks_per_tile_x_row;            // 0..7

#pragma unroll
    for (int i0 = 0; i0 < mmq_y; i0 += nwarps * rows_per_warp) {
        int i = i0 + threadIdx.y * rows_per_warp + threadIdx.x / blocks_per_tile_x_row;

        if (need_check) {
            i = min(i, i_max);
        }

        // Two WQ3_TCQ blocks per tile; kbxd/4 picks which block's norm to use.
        const block_turboq3_tcq * bxi = (const block_turboq3_tcq *) x + kbx0 + i*stride + (kbxd >> 2);
        const float scale = __half2float(bxi->norm) * d_wq3_tcq_codebook_scale;

#if defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
        x_df[i*MMQ_MMA_TILE_X_K_Q8_0                 + kbxd] = scale;
#else
        x_df[i*(2*MMQ_TILE_NE_K/QI8_0) + i/(QI8_0/2) + kbxd] = scale;
#endif // defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
    }
}

template <int mmq_x, int mmq_y, bool need_check>
struct mmq_type_traits<mmq_x, mmq_y, need_check, GGML_TYPE_WQ3_TCQ> {
    static constexpr int              vdr          = VDR_Q8_0_Q8_1_MMQ;
    static constexpr load_tiles_mmq_t load_tiles   = load_tiles_wq3_tcq<mmq_y, need_check>;
    static constexpr vec_dot_mmq_t    vec_dot_mma  = vec_dot_q8_0_q8_1_mma<mmq_x, mmq_y, MMQ_Q8_1_DS_LAYOUT_D4>;
    static constexpr vec_dot_mmq_t    vec_dot_dp4a = vec_dot_q8_0_q8_1_dp4a<mmq_x, mmq_y>;
};

DECL_MMQ_CASE(GGML_TYPE_WQ3_TCQ);
