#!/usr/bin/env python3
import os
import sys

def main():
    types = [
        "GGML_TYPE_TURBOQ8_0",
        "GGML_TYPE_TURBOQ6_0",
        "GGML_TYPE_TURBOQ5_0",
        "GGML_TYPE_TURBOQ4_0",
        "GGML_TYPE_TURBOQ3_0",
        "GGML_TYPE_TURBOQ2_0",
    ]
    
    pairs = []
    for i in range(len(types)):
        for j in range(i, len(types)):
            pairs.append((types[i], types[j]))

    dims = [128, 256]
    ncols_set = [(1,8), (2,8), (4,8), (2,4), (4,4), (4,2), (8,1)]
    
    out_file = "ggml/src/ggml-cuda/fattn-mma-native-turbo.cu"
    
    content = "// AUTO-GENERATED BY scripts/codegen_fattn_mma.py\n\n"
    content += "#include \"fattn-mma-f16.cuh\"\n"
    content += "#include \"fattn-mma-turbo.cuh\"\n\n"
    
    for tk, tv in pairs:
        for d in dims:
            for c1, c2 in ncols_set:
                content += f"DECL_FATTN_MMA_TURBO_CASE({d}, {d}, {c1}, {c2}, {tk}, {tv});\n"
            
    with open(out_file, "w") as f:
        f.write(content)

    print(f"Generated {out_file}")

if __name__ == "__main__":
    main()
